### ISSUE TITLE
Installing on 10.12

### ISSUE THREAD

**Issue by washu** [phusion/homebrew-passenger-enterprise#2]
```
==> Installing passenger-enterprise from phusion/passenger
==> Installing dependencies for phusion/passenger/passenger-enterprise: pcre
==> Installing phusion/passenger/passenger-enterprise dependency: pcre
==> Downloading https://homebrew.bintray.com/bottles/pcre-8.42.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring pcre-8.42.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/pcre/8.42: 204 files, 5.3MB
==> Installing phusion/passenger/passenger-enterprise
==> Downloading https://www.phusionpassenger.com/orders/download?dir=6.0.1&file=passenger-enterprise-server-6.0.1.tar.gz
######################################################################## 100.0%
==> rake apache2
Last 15 lines from /Users/washu/Library/Logs/Homebrew/passenger-enterprise/01.rake:
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:1091:in `block in have_header'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:1090:in `have_header'
	from /private/tmp/passenger-enterprise-20190108-10391-18abnhy/passenger-enterprise-server-6.0.1/src/ruby_native_extension/extconf.rb:22:in `<main>'
rake aborted!
Command failed with status (1): [cd 'buildout/ruby/ruby-2.3.7-universal-mac...]
/private/tmp/passenger-enterprise-20190108-10391-18abnhy/passenger-enterprise-server-6.0.1/build/ruby_extension.rb:40:in `block in <top (required)>'
Tasks: TOP => apache2 => buildout/ruby/ruby-2.3.7-universal-macosx/passenger_native_support.bundle => buildout/ruby/ruby-2.3.7-universal-macosx/Makefile
(See full trace by running task with --trace)

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/phusion/homebrew-passenger/issues

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:250:in `raise_api_error': Validation Failed: [{"message"=>"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource"=>"Search", "field"=>"q", "code"=>"invalid"}] (GitHub::ValidationFailedError)
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:206:in `open_api'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:324:in `search'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:257:in `search_issues'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:270:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:372:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:368:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:422:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:127:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:17:in `<main>'
```

**Comment by CamJN** [comment]
This looks similar to what some people experienced here: https://github.com/Homebrew/homebrew-core/issues/34002

Of course you're on a different release of macOS, but perhaps there's some usable insight. Do you have the full xcode installed or the cli tool package? If it's xcode have you opened it since the last update (to trigger the "installing support packages" process? If it's the cli package, can you check if it contains a SDK headers package in the install? 

`find /Library/Developer/CommandLineTools/ -name '*.pkg'`

**Comment by washu** [comment]
that directory is empty, but i doubled checked and i do have both xcode and the cli instaleld and opened up.

**Comment by washu** [comment]
Sals-iMac:aztec-olympus washu$ xcode-select --version
xcode-select version 2347.
Sals-iMac:aztec-olympus washu$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
Sals-iMac:aztec-olympus washu$ pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 9.2.0.0.1.1510905681
volume: /
location: /
install-time: 1546973405
groups: com.apple.FindSystemFiles.pkg-group

**Comment by CamJN** [comment]
What does `pkgutil --pkgs | fgrep -i SDK` print?

**Comment by washu** [comment]
com.apple.pkg.CLTools_SDK_macOS1013
com.apple.pkg.CLTools_SDK_macOSSDK
com.apple.pkg.CLTools_SDK_OSX1012
com.apple.pkg.DevSDK
com.apple.pkg.DevSDK_OSX1012
com.apple.pkg.OSXSDK10.12

**Comment by CamJN** [comment]
Do you use rvm or rbenv or something else to manage you rubies? Or do you use the system ruby (our installer in homebrew uses the system ruby, but I'm talking about in your normal shell)?

If you use a non system ruby could you run a shell with no profile then see if homebrew can build passenger? eg. `env -i HOME="$HOME" bash --login  --noprofile --norc  /usr/local/bin/brew install passenger-enterprise`

I'm wondering if homebrew picks up on the gem installed passenger and somehow includes parts of it.

**Comment by washu** [comment]
i use rbenv

**Comment by washu** [comment]
tried command same result

**Comment by washu** [comment]
details! 
apxs:Error: /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/local/bin/apr-1-config not found!.

**Comment by CamJN** [comment]
Ah, ok can you tell me what this command prints?
`find $(xcode-select -p) -name apr-1-config`

**Comment by washu** [comment]
https://github.com/Homebrew/homebrew-php/issues/3283#issuecomment-249886457

fixes the compiler error related to apache apr, but i still error out in the build.
```
mkdir -p 'buildout/ruby/ruby-2.3.7-universal-macosx/'
cd 'buildout/ruby/ruby-2.3.7-universal-macosx/' && /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby '/private/tmp/passenger-enterprise-20190109-80725-gpbdg8/passenger-enterprise-server-6.0.1/src/ruby_native_extension/extconf.rb'
checking for alloca.h... *** /private/tmp/passenger-enterprise-20190109-80725-gpbdg8/passenger-enterprise-server-6.0.1/src/ruby_native_extension/extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=/private/tmp/passenger-enterprise-20190109-80725-gpbdg8/passenger-enterprise-server-6.0.1/src/ruby_native_extension
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/$(RUBY_BASE_NAME)
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:571:in `block in try_compile'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:524:in `with_werror'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:571:in `try_compile'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:1091:in `block in have_header'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:1090:in `have_header'
	from /private/tmp/passenger-enterprise-20190109-80725-gpbdg8/passenger-enterprise-server-6.0.1/src/ruby_native_extension/extconf.rb:22:in `<main>'
rake aborted!
```

But i have xcode,clang installed

**Comment by CamJN** [comment]
And this command works for you?
`env -i HOME="$HOME" bash --login --noprofile --norc -c '/usr/bin/ruby -rmkmf -e "puts have_header(\"alloca.h\")"'`

**Comment by washu** [comment]
```
checking for alloca.h... /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:571:in `block in try_compile'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:524:in `with_werror'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:571:in `try_compile'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:1091:in `block in have_header'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:1090:in `have_header'
	from -e:1:in `<main>'
```

**Comment by washu** [comment]
If I however extract the cached download of pasenger and run rake nginx that runs and build without issue, and build nginx as well

**Comment by washu** [comment]
i did notice when i built using the system framework it built using those ruby headers, and when i went to run under rbenv ruby 2.6 i get `The application encountered the following error: Your Ruby version is 2.4.0, but your Gemfile specified 2.6.0 (Bundler::RubyVersionMismatch)` as an error since im using 5.2 with 2.6 and rubygems 3 which sets the ruby version. meaning to me in standalone where does it lookup the ruby interpreter path? is it a static link

**Comment by washu** [comment]
this maybe related to system defuault ruby on sierra is ruby 2.3 causing the missing headers

**Comment by CamJN** [comment]
Apparently the sierra CLI tools contain the headers, but do not install them to the expected location in the system. 

Adding `C_INCLUDE_PATH=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Headers` to the environment works for me in a sierra VM to allow mkmf to find the headers it wants.

**Comment by CamJN** [comment]
Should be fixed in https://github.com/phusion/passenger/commit/3105d7c1fb92cc3c8e873cbfd9343837fcfa74db
